#!/bin/bash

# 🚀 FireReport - Testing & Deployment Quick Start

echo "=================================="
echo "FireReport Testing & Deployment"
echo "=================================="
echo ""

# 1. Verificar que todo está instalado
echo "📦 Verificando dependencias..."
npm list @react-native-community/netinfo > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "✅ NetInfo instalado"
else
  echo "❌ NetInfo no encontrado. Instalando..."
  npm install @react-native-community/netinfo
fi

echo ""
echo "=================================="
echo "TESTING LOCAL (Desktop)"
echo "=================================="
echo ""
echo "1️⃣  INICIAR SERVIDOR EXPO"
echo "Ejecuta en terminal:"
echo "  npx expo start"
echo ""
echo "Luego presiona:"
echo "  'a' para Android Emulator"
echo "  'i' para iOS Simulator (Mac)"
echo "  'w' para Web"
echo ""

echo "2️⃣  TESTING DE FUNCIONALIDAD"
echo "Verifica que:"
echo "  ✓ Cada reporte se abre sin errores"
echo "  ✓ Puedes llenar datos"
echo "  ✓ Puedes tomar fotos"
echo "  ✓ Guardar funciona"
echo "  ✓ Modales de firma funcionan"
echo ""

echo "3️⃣  TESTING VISUAL"
echo "Verifica que:"
echo "  ✓ Headers son rojos (#d32f2f)"
echo "  ✓ Tabs son blancos con indicadores rojos"
echo "  ✓ Botones: Azul para guardar, Rojo para PDF"
echo "  ✓ Inputs tienen bordes grises"
echo "  ✓ Modales son consistentes en los 3 reportes"
echo ""

echo "=================================="
echo "TESTING OFFLINE-FIRST"
echo "=================================="
echo ""
echo "1️⃣  ACTIVAR AIRPLANE MODE"
echo "  En emulador: Settings → Network → Airplane Mode ON"
echo ""
echo "2️⃣  CREAR REPORTE OFFLINE"
echo "  - Crea un reporte con fotos"
echo "  - Presiona 'GUARDAR BORRADOR'"
echo "  - Esperado: 'Se sincronizará con nube cuando tengas internet'"
echo "  - Verifica que aparece en Historial"
echo ""
echo "3️⃣  DESACTIVAR AIRPLANE MODE"
echo "  - Sin cerrar la app"
echo "  - Abre Developer Console (Ctrl+D)"
echo "  - Busca logs con 'NetworkListener'"
echo "  - Deberías ver: 'Successfully synced X report(s)'"
echo ""

echo "=================================="
echo "BUILD APK"
echo "=================================="
echo ""
echo "Opción 1: Build Preview (para testing)"
echo "  eas build --platform android --profile preview"
echo ""
echo "Opción 2: Build Production (con certificado)"
echo "  eas build --platform android --profile production"
echo ""

echo "=================================="
echo "INSTALACIÓN EN DISPOSITIVO"
echo "=================================="
echo ""
echo "Desde Expo Dashboard:"
echo "  1. Espera a que el build termine"
echo "  2. Haz clic en 'Download'"
echo "  3. El APK se descarga"
echo "  4. Abre con tu dispositivo o emulador"
echo ""
echo "O vía ADB:"
echo "  adb install /path/to/app.apk"
echo ""

echo "=================================="
echo "STATUS ACTUAL"
echo "=================================="
echo ""
echo "✅ Offline-first architecture completa"
echo "✅ Image limit enforcement (1500 máximo)"
echo "✅ Auto-sync con NetInfo"
echo "✅ Estilo visual unificado"
echo "✅ Backup queue system"
echo "✅ Supabase integration"
echo ""

echo "Documentación disponible:"
echo "  - TESTING_AND_DEPLOYMENT.md"
echo "  - OFFLINE_FIRST_QUICK_START.md"
echo "  - COLOR_PALETTE.md"
echo ""

echo "=================================="
echo "¡Listo para testing! 🚀"
echo "=================================="
